# Basic Numpy Operation 1D

In [43]:
import numpy as np
a1=np.array([26,4,7,43,6,80,5,21])
print('array',a1)
print('size',a1.size)
print('shape',a1.shape)
print('sorting',np.sort(a1))
print('Reverse',np.flip(a1))
print('Dimension',a1.ndim)
print('Type',type(a1))
print('Indexing',a1[6])
print('Fancy Indexing',a1[[2,5,0]])
print('slicing',a1[2:5])
print('Ventorization',a1*3)
print('element wise operation',a1[:4]*2)
print('Split',np.split(a1,[2,5]))
print('square_root',np.sqrt(a1))
print('exponent',np.exp(a1)) #a1**any number (alternate method)
print('absolute value',np.abs(a1))
print('round off',np.rint(a1))


array [26  4  7 43  6 80  5 21]
size 8
shape (8,)
sorting [ 4  5  6  7 21 26 43 80]
Reverse [21  5 80  6 43  7  4 26]
Dimension 1
Type <class 'numpy.ndarray'>
Indexing 5
Fancy Indexing [ 7 80 26]
slicing [ 7 43  6]
Ventorization [ 78  12  21 129  18 240  15  63]
element wise operation [52  8 14 86]
Split [array([26,  4]), array([ 7, 43,  6]), array([80,  5, 21])]
square_root [5.09901951 2.         2.64575131 6.55743852 2.44948974 8.94427191
 2.23606798 4.58257569]
exponent [1.95729609e+11 5.45981500e+01 1.09663316e+03 4.72783947e+18
 4.03428793e+02 5.54062238e+34 1.48413159e+02 1.31881573e+09]
absolute value [26  4  7 43  6 80  5 21]
round off [26.  4.  7. 43.  6. 80.  5. 21.]


# 2D

In [8]:
import numpy as np
a2=np.array([[[26,4,7],[43,6,80]]
            ,[[5,21,6],[5,1,0]]])
print('array',a2)
print('size',a2.size)
print('shape',a2.shape)
print('sorting',np.sort(a2))
print('Reverse',np.flip(a2))
print('Dimension',a2.ndim)
print('Type',type(a2))
print('Indexing',a2[1])
print('Fancy Indexing',a2[[0,1]])
print('slicing',a2[:2])
print('Ventorization',a2*3)
print('element wise operation',a2[:2]*2)

array [[[26  4  7]
  [43  6 80]]

 [[ 5 21  6]
  [ 5  1  0]]]
size 12
shape (2, 2, 3)
sorting [[[ 4  7 26]
  [ 6 43 80]]

 [[ 5  6 21]
  [ 0  1  5]]]
Reverse [[[ 0  1  5]
  [ 6 21  5]]

 [[80  6 43]
  [ 7  4 26]]]
Dimension 3
Type <class 'numpy.ndarray'>
Indexing [[ 5 21  6]
 [ 5  1  0]]
Fancy Indexing [[[26  4  7]
  [43  6 80]]

 [[ 5 21  6]
  [ 5  1  0]]]
slicing [[[26  4  7]
  [43  6 80]]

 [[ 5 21  6]
  [ 5  1  0]]]
Ventorization [[[ 78  12  21]
  [129  18 240]]

 [[ 15  63  18]
  [ 15   3   0]]]
element wise operation [[[ 52   8  14]
  [ 86  12 160]]

 [[ 10  42  12]
  [ 10   2   0]]]


# Text Spliting

In [10]:
import numpy as np
txt = """"Here are some of the things you’ll find in NumPy:
• ndarray, an efficient multidimensional array providing fast array-oriented arith‐
metic operations and flexible broadcasting capabilities.
• Mathematical functions for fast operations on entire arrays of data without hav‐
ing to write loops."""""
a3=np.array(txt.split())
print(type(a3))
print(a3[:15], '\n',len(a3))

<class 'numpy.ndarray'>
['"Here' 'are' 'some' 'of' 'the' 'things' 'you’ll' 'find' 'in' 'NumPy:'
 '•' 'ndarray,' 'an' 'efficient' 'multidimensional'] 
 43


# Arithmetic Operations on Arrays

In [45]:
x=np.array([[6,9,3,5],[1,5,0,6]])
y=np.array([[1,2,3,4],[5,3,2,1]])
add = x+y
sub=x-y
mult=x*y
div=x/y
print(add,'\n',sub,'\n',mult,'\n',div)
print(np.maximum(x,y))
print(np.minimum(x,y))

[[ 7 11  6  9]
 [ 6  8  2  7]] 
 [[ 5  7  0  1]
 [-4  2 -2  5]] 
 [[ 6 18  9 20]
 [ 5 15  0  6]] 
 [[6.         4.5        1.         1.25      ]
 [0.2        1.66666667 0.         6.        ]]
[[6 9 3 5]
 [5 5 2 6]]
[[1 2 3 4]
 [1 3 0 1]]


# Boolean Array

In [17]:
x=np.array([[6,9,3,5],[1,5,0,6]])
y=np.array([[1,2,3,4],[5,3,2,1]])
add = x+y
boolean=(x==y)  #we use boolean array for filtering data
# when we compare 2 arrays through equality operator '='. It goves us a Boolean array in return
print(boolean)
boolean=add>8

arrayfilter1=boolean
print(arrayfilter1)

arrayfilter=add[boolean]
print(arrayfilter)

[[False False  True False]
 [False False False False]]
[[False  True False  True]
 [False False False False]]
[11  9]


# Different Shapes of Array

In [71]:
a4=np.zeros([2,3,5])
print(a4)
print(a4.shape)
print(a4.size)
print(a4.ndim)
print(a4.ravel())
printa4.flatten()

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
(2, 3, 5)
30
3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
a4.fill(3)
a4

array([[[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]],


       [[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]]])

In [41]:
a4[0,2,3,0]=1 #0 indicates 0 n 1 index then2 indicates 0 1 2 index then3 indicates 0 1 2 3 index and then last 0 indicates 0 1 2  3 4 index
a4

array([[[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [1., 9., 9., 9., 9.]]],


       [[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]]])

In [81]:
a5=np.random.rand(5,5,2)
print(a5)
print(a5.shape)
print(a5.ndim)
a5.flatten()
r=a5.reshape(25,2)
print(r)
print(r.shape)
print(r.size)

[[[0.57599622 0.07224621]
  [0.59371462 0.09980974]
  [0.16611594 0.33463599]
  [0.70392147 0.04109214]
  [0.26590773 0.37658154]]

 [[0.48949418 0.0664758 ]
  [0.72049693 0.96858562]
  [0.89560853 0.93220164]
  [0.66926423 0.77915128]
  [0.48041599 0.13389517]]

 [[0.30356262 0.32553491]
  [0.0301912  0.98292973]
  [0.71236202 0.19369329]
  [0.67766605 0.71344668]
  [0.23810005 0.959025  ]]

 [[0.57043414 0.8564727 ]
  [0.21788302 0.76742535]
  [0.56877135 0.23894033]
  [0.71217317 0.78826656]
  [0.80308029 0.88413055]]

 [[0.43188915 0.22290378]
  [0.86715082 0.29803628]
  [0.98968894 0.63611182]
  [0.91295475 0.1855911 ]
  [0.55577951 0.40036513]]]
(5, 5, 2)
3
[[0.57599622 0.07224621]
 [0.59371462 0.09980974]
 [0.16611594 0.33463599]
 [0.70392147 0.04109214]
 [0.26590773 0.37658154]
 [0.48949418 0.0664758 ]
 [0.72049693 0.96858562]
 [0.89560853 0.93220164]
 [0.66926423 0.77915128]
 [0.48041599 0.13389517]
 [0.30356262 0.32553491]
 [0.0301912  0.98292973]
 [0.71236202 0.19369329]
 [0

In [59]:
np.random.shuffle(a5)
a5


array([[0.98139525, 0.08255405, 0.88253804, 0.473489  , 0.99945558],
       [0.23214432, 0.88587875, 0.3750585 , 0.83735347, 0.84249864],
       [0.28097963, 0.96116615, 0.61006715, 0.10074896, 0.557611  ],
       [0.02658959, 0.00590639, 0.99342252, 0.59772761, 0.44875111],
       [0.98566183, 0.03217617, 0.72827979, 0.18269968, 0.47875316]])

In [60]:
a6=np.arange(15)
a6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
a5.ravel()

array([0.98139525, 0.08255405, 0.88253804, 0.473489  , 0.99945558,
       0.23214432, 0.88587875, 0.3750585 , 0.83735347, 0.84249864,
       0.28097963, 0.96116615, 0.61006715, 0.10074896, 0.557611  ,
       0.02658959, 0.00590639, 0.99342252, 0.59772761, 0.44875111,
       0.98566183, 0.03217617, 0.72827979, 0.18269968, 0.47875316])

In [85]:
np.random.seed(2)
print(np.random.rand(3,3))


[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]
 [0.20464863 0.61927097 0.29965467]]


# Transpose and Swapping Axes

In [125]:
import numpy as np
a8=np.random.rand(4,4)
a8

array([[0.59604912, 0.09190485, 0.89560999, 0.46227594],
       [0.44481236, 0.1047113 , 0.68490404, 0.81689399],
       [0.62955017, 0.24202261, 0.78542072, 0.14567943],
       [0.82727633, 0.58070537, 0.28937281, 0.5132434 ]])

In [126]:
a8.T

array([[0.59604912, 0.44481236, 0.62955017, 0.82727633],
       [0.09190485, 0.1047113 , 0.24202261, 0.58070537],
       [0.89560999, 0.68490404, 0.78542072, 0.28937281],
       [0.46227594, 0.81689399, 0.14567943, 0.5132434 ]])

In [127]:
a8.fill(6)
a8

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [128]:
a9=a8.reshape(4,2,2)
a9

array([[[6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.]]])

In [150]:
a9.swapaxes(1,0)


array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [147]:
a9.transpose(1,0,2)

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [22]:
a11=np.ones([3,4,2,5])

a11

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [30]:
a12=np.array([[[6,9,3,5],[1,5,0,6]],
             [[1,2,3,4],[5,3,2,1]]])
a12.transpose((0,2,1))  #Here 1 2 0 are axeses

array([[[6, 1],
        [9, 5],
        [3, 0],
        [5, 6]],

       [[1, 5],
        [2, 3],
        [3, 2],
        [4, 1]]])

In [40]:
a13=np.array([1.1,2.7])
print(np.rint(a13)) #Round off

[1. 3.]


# Filing

In [101]:
import numpy as np
x=[1,2,3,4]
y=[9,8,6,5]
np.save('Demofile',y)
load=np.load('Demofile.npy')
load

array([9, 8, 6, 5])

In [103]:
np.savez('Demofilexy',x,y)
loadxy=np.load('Demofilexy.npz')
loadxy




# Split Function in 2D 

In [30]:
z=[[3,4,7,9,1],[23,24,27,29,21]]
a14=np.array(z)
np.split(a14,[1,3],axis=1)


[array([[ 3],
        [23]]), array([[ 4,  7],
        [24, 27]]), array([[ 9,  1],
        [29, 21]])]

In [31]:
np.split(a14,[1,3],axis=0)

[array([[3, 4, 7, 9, 1]]),
 array([[23, 24, 27, 29, 21]]),
 array([], shape=(0, 5), dtype=int32)]

# Repeat and Tile

In [32]:
a15=np.array([5,8,2])
np.repeat(a15,4)

array([5, 5, 5, 5, 8, 8, 8, 8, 2, 2, 2, 2])

In [33]:
np.tile(a15,3)

array([5, 8, 2, 5, 8, 2, 5, 8, 2])

# Concatenation

In [38]:
x=np.array([[1,2],[3,4]])
y=np.array([[9,8],[6,5]])
np.concatenate((x,y),axis=1) #column wise concatenate

array([[1, 2, 9, 8],
       [3, 4, 6, 5]])

In [39]:
np.concatenate((x,y),axis=0) #Row wise concatenate

array([[1, 2],
       [3, 4],
       [9, 8],
       [6, 5]])

In [40]:
np.hstack((x,y)) #Column wise concatenate

array([[1, 2, 9, 8],
       [3, 4, 6, 5]])

In [41]:
np.vstack((x,y)) #Row wise concatenate

array([[1, 2],
       [3, 4],
       [9, 8],
       [6, 5]])

In [42]:
a16=np.random.rand(3,4)
print(a16)

[[0.03836976 0.79545161 0.77789848 0.38135509]
 [0.78354    0.15645819 0.74006714 0.88853763]
 [0.32374987 0.85688583 0.04034633 0.34992445]]


# Reshape

In [46]:
a16.reshape(3,2,2,order='F') # F represent fortran that is column wise operation

array([[[0.03836976, 0.77789848],
        [0.79545161, 0.38135509]],

       [[0.78354   , 0.74006714],
        [0.15645819, 0.88853763]],

       [[0.32374987, 0.04034633],
        [0.85688583, 0.34992445]]])

In [45]:
a16.reshape(3,2,-1,order='C') #C represnt row wise operation and -1 generates its own value in reshaping

array([[[0.03836976, 0.79545161],
        [0.77789848, 0.38135509]],

       [[0.78354   , 0.15645819],
        [0.74006714, 0.88853763]],

       [[0.32374987, 0.85688583],
        [0.04034633, 0.34992445]]])

# Pseudo Random Number

In [89]:
import numpy as np
np.random.seed(7)
np.random.rand(2,5)


array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951],
       [0.53849587, 0.50112046, 0.07205113, 0.26843898, 0.4998825 ]])

In [88]:
np.random.normal(size=(4,4)) #It generates normal given input array

array([[-0.62542897, -0.17154826,  0.50529937, -0.26135642],
       [-0.24274908, -1.45324141,  0.55458031,  0.12388091],
       [ 0.27445992, -1.52652453,  1.65069969,  0.15433554],
       [-0.38713994,  2.02907222, -0.04538603, -1.4506787 ]])

In [20]:
np.random.gamma(6)

4.961429659589471

In [81]:
np.random.uniform(3,8) #This function returns a floating point random number between two parameters.

5.707210660476099

In [82]:
np.random.randint(5,20)   #It generates the random number between the given range that is 5 to 20 
#random.randint(start,end)

16

In [68]:
np.random.choice(range(50)) #This function picks a random number from the range. If the sequence is empty, IndexError is thrown.


12

In [69]:
np.random.choice([2,5,8,0,1,6,7])  #This function picks a random element from the sequence. If the sequence is empty, IndexError is thrown.

5

In [78]:
r=[23,45,76,1,0,6,11] #This function reorders elements in a mutable sequence and places them randomly.
np.random.shuffle(r)
r

[76, 6, 45, 11, 23, 0, 1]

In [83]:
np.random.random() #it genrates the floating number between 0 to 1

0.4036485763523965

# Linear Algebra Function

In [92]:
a18=np.random.rand(3,4)
a19=np.random.rand(4,3)

In [93]:
a18.dot(a19)

array([[0.92450756, 0.84385601, 1.02252908],
       [1.11754439, 1.03618163, 1.0115703 ],
       [0.9054396 , 1.05110557, 0.95222567]])

In [94]:
a18.diagonal()

array([0.66901324, 0.47740115, 0.57262533])

In [98]:
print(a19)
a19.transpose()

[[0.45284293 0.35297837 0.65739946]
 [0.37035108 0.45909298 0.71932412]
 [0.41299183 0.90642327 0.18045162]
 [0.74111887 0.42237404 0.42645357]]


array([[0.45284293, 0.37035108, 0.41299183, 0.74111887],
       [0.35297837, 0.45909298, 0.90642327, 0.42237404],
       [0.65739946, 0.71932412, 0.18045162, 0.42645357]])

In [99]:
print(a19)
a19.T

[[0.45284293 0.35297837 0.65739946]
 [0.37035108 0.45909298 0.71932412]
 [0.41299183 0.90642327 0.18045162]
 [0.74111887 0.42237404 0.42645357]]


array([[0.45284293, 0.37035108, 0.41299183, 0.74111887],
       [0.35297837, 0.45909298, 0.90642327, 0.42237404],
       [0.65739946, 0.71932412, 0.18045162, 0.42645357]])

In [112]:
a20=np.random.rand(2,3,4)
print(a20)
a20.T

[[[0.65012833 0.59562111 0.75195356 0.06166533]
  [0.74482367 0.94627593 0.60355955 0.28757994]
  [0.67236922 0.71204879 0.65645029 0.14693032]]

 [[0.97347557 0.95538345 0.42462553 0.59363733]
  [0.03962857 0.98863433 0.81874499 0.63650234]
  [0.76108474 0.18802993 0.30765459 0.24639364]]]


array([[[0.65012833, 0.97347557],
        [0.74482367, 0.03962857],
        [0.67236922, 0.76108474]],

       [[0.59562111, 0.95538345],
        [0.94627593, 0.98863433],
        [0.71204879, 0.18802993]],

       [[0.75195356, 0.42462553],
        [0.60355955, 0.81874499],
        [0.65645029, 0.30765459]],

       [[0.06166533, 0.59363733],
        [0.28757994, 0.63650234],
        [0.14693032, 0.24639364]]])

In [124]:
a20.transpose(0,2,1)

array([[[0.65012833, 0.74482367, 0.67236922],
        [0.59562111, 0.94627593, 0.71204879],
        [0.75195356, 0.60355955, 0.65645029],
        [0.06166533, 0.28757994, 0.14693032]],

       [[0.97347557, 0.03962857, 0.76108474],
        [0.95538345, 0.98863433, 0.18802993],
        [0.42462553, 0.81874499, 0.30765459],
        [0.59363733, 0.63650234, 0.24639364]]])

In [151]:
a20.swapaxes(1,0)

array([[[0.65012833, 0.59562111, 0.75195356, 0.06166533],
        [0.97347557, 0.95538345, 0.42462553, 0.59363733]],

       [[0.74482367, 0.94627593, 0.60355955, 0.28757994],
        [0.03962857, 0.98863433, 0.81874499, 0.63650234]],

       [[0.67236922, 0.71204879, 0.65645029, 0.14693032],
        [0.76108474, 0.18802993, 0.30765459, 0.24639364]]])

# Mathematical and Statistical Methods

In [137]:
a21=np.array([9,4,2,1,22,77,44])
a21.mean()

22.714285714285715

In [138]:
a21.cumsum()

array([  9,  13,  15,  16,  38, 115, 159], dtype=int32)

In [139]:
a21.cumprod()

array([      9,      36,      72,      72,    1584,  121968, 5366592],
      dtype=int32)

In [140]:
a22=a21>20
a22

array([False, False, False, False,  True,  True,  True])

In [141]:
a22.sum() #Total count of true values

3

In [142]:
a22.all() #all elements in array are true ??

False

In [143]:
a22.any() #any element in array is true?

True

In [157]:
a23=np.random.rand(4,2,2)
a23

array([[[0.73142128, 0.52370801],
        [0.0925818 , 0.10605922]],

       [[0.14922495, 0.16120001],
        [0.05275579, 0.04701317]],

       [[0.9484283 , 0.09129179],
        [0.50835168, 0.11862982]],

       [[0.21478785, 0.76307207],
        [0.93813482, 0.46971269]]])

In [160]:
a23.swapaxes(0,1)

array([[[0.73142128, 0.52370801],
        [0.14922495, 0.16120001],
        [0.9484283 , 0.09129179],
        [0.21478785, 0.76307207]],

       [[0.0925818 , 0.10605922],
        [0.05275579, 0.04701317],
        [0.50835168, 0.11862982],
        [0.93813482, 0.46971269]]])

In [163]:
a21.sort()
a21

array([ 1,  2,  4,  9, 22, 44, 77])

In [164]:
np.unique(a21)

array([ 1,  2,  4,  9, 22, 44, 77])