# Basic Numpy Operation 1D

In [4]:
import numpy as np
a1=np.array([26,4,7,43,6,80,5,21])
print('array',a1)
print('size',a1.size)
print('shape',a1.shape)
print('sorting',np.sort(a1))
print('Reverse',np.flip(a1))
print('Dimension',a1.ndim)
print('Type',type(a1))
print('Indexing',a1[6])
print('Fancy Indexing',a1[[2,5,0]])
print('slicing',a1[2:5])
print('Ventorization',a1*3)
print('element wise operation',a1[:4]*2)
print('Split',np.split(a1,[2,5]))

array [26  4  7 43  6 80  5 21]
size 8
shape (8,)
sorting [ 4  5  6  7 21 26 43 80]
Reverse [21  5 80  6 43  7  4 26]
Dimension 1
Type <class 'numpy.ndarray'>
Indexing 5
Fancy Indexing [ 7 80 26]
slicing [ 7 43  6]
Ventorization [ 78  12  21 129  18 240  15  63]
element wise operation [52  8 14 86]
Split [array([26,  4]), array([ 7, 43,  6]), array([80,  5, 21])]


# 2D

In [8]:
import numpy as np
a2=np.array([[[26,4,7],[43,6,80]]
            ,[[5,21,6],[5,1,0]]])
print('array',a2)
print('size',a2.size)
print('shape',a2.shape)
print('sorting',np.sort(a2))
print('Reverse',np.flip(a2))
print('Dimension',a2.ndim)
print('Type',type(a2))
print('Indexing',a2[1])
print('Fancy Indexing',a2[[0,1]])
print('slicing',a2[:2])
print('Ventorization',a2*3)
print('element wise operation',a2[:2]*2)

array [[[26  4  7]
  [43  6 80]]

 [[ 5 21  6]
  [ 5  1  0]]]
size 12
shape (2, 2, 3)
sorting [[[ 4  7 26]
  [ 6 43 80]]

 [[ 5  6 21]
  [ 0  1  5]]]
Reverse [[[ 0  1  5]
  [ 6 21  5]]

 [[80  6 43]
  [ 7  4 26]]]
Dimension 3
Type <class 'numpy.ndarray'>
Indexing [[ 5 21  6]
 [ 5  1  0]]
Fancy Indexing [[[26  4  7]
  [43  6 80]]

 [[ 5 21  6]
  [ 5  1  0]]]
slicing [[[26  4  7]
  [43  6 80]]

 [[ 5 21  6]
  [ 5  1  0]]]
Ventorization [[[ 78  12  21]
  [129  18 240]]

 [[ 15  63  18]
  [ 15   3   0]]]
element wise operation [[[ 52   8  14]
  [ 86  12 160]]

 [[ 10  42  12]
  [ 10   2   0]]]
