# Basic Numpy Operation 1D

In [43]:
import numpy as np
a1=np.array([26,4,7,43,6,80,5,21])
print('array',a1)
print('size',a1.size)
print('shape',a1.shape)
print('sorting',np.sort(a1))
print('Reverse',np.flip(a1))
print('Dimension',a1.ndim)
print('Type',type(a1))
print('Indexing',a1[6])
print('Fancy Indexing',a1[[2,5,0]])
print('slicing',a1[2:5])
print('Ventorization',a1*3)
print('element wise operation',a1[:4]*2)
print('Split',np.split(a1,[2,5]))
print('square_root',np.sqrt(a1))
print('exponent',np.exp(a1)) #a1**any number (alternate method)
print('absolute value',np.abs(a1))
print('round off',np.rint(a1))


array [26  4  7 43  6 80  5 21]
size 8
shape (8,)
sorting [ 4  5  6  7 21 26 43 80]
Reverse [21  5 80  6 43  7  4 26]
Dimension 1
Type <class 'numpy.ndarray'>
Indexing 5
Fancy Indexing [ 7 80 26]
slicing [ 7 43  6]
Ventorization [ 78  12  21 129  18 240  15  63]
element wise operation [52  8 14 86]
Split [array([26,  4]), array([ 7, 43,  6]), array([80,  5, 21])]
square_root [5.09901951 2.         2.64575131 6.55743852 2.44948974 8.94427191
 2.23606798 4.58257569]
exponent [1.95729609e+11 5.45981500e+01 1.09663316e+03 4.72783947e+18
 4.03428793e+02 5.54062238e+34 1.48413159e+02 1.31881573e+09]
absolute value [26  4  7 43  6 80  5 21]
round off [26.  4.  7. 43.  6. 80.  5. 21.]


# 2D

In [8]:
import numpy as np
a2=np.array([[[26,4,7],[43,6,80]]
            ,[[5,21,6],[5,1,0]]])
print('array',a2)
print('size',a2.size)
print('shape',a2.shape)
print('sorting',np.sort(a2))
print('Reverse',np.flip(a2))
print('Dimension',a2.ndim)
print('Type',type(a2))
print('Indexing',a2[1])
print('Fancy Indexing',a2[[0,1]])
print('slicing',a2[:2])
print('Ventorization',a2*3)
print('element wise operation',a2[:2]*2)

array [[[26  4  7]
  [43  6 80]]

 [[ 5 21  6]
  [ 5  1  0]]]
size 12
shape (2, 2, 3)
sorting [[[ 4  7 26]
  [ 6 43 80]]

 [[ 5  6 21]
  [ 0  1  5]]]
Reverse [[[ 0  1  5]
  [ 6 21  5]]

 [[80  6 43]
  [ 7  4 26]]]
Dimension 3
Type <class 'numpy.ndarray'>
Indexing [[ 5 21  6]
 [ 5  1  0]]
Fancy Indexing [[[26  4  7]
  [43  6 80]]

 [[ 5 21  6]
  [ 5  1  0]]]
slicing [[[26  4  7]
  [43  6 80]]

 [[ 5 21  6]
  [ 5  1  0]]]
Ventorization [[[ 78  12  21]
  [129  18 240]]

 [[ 15  63  18]
  [ 15   3   0]]]
element wise operation [[[ 52   8  14]
  [ 86  12 160]]

 [[ 10  42  12]
  [ 10   2   0]]]


# Text Spliting

In [10]:
import numpy as np
txt = """"Here are some of the things you’ll find in NumPy:
• ndarray, an efficient multidimensional array providing fast array-oriented arith‐
metic operations and flexible broadcasting capabilities.
• Mathematical functions for fast operations on entire arrays of data without hav‐
ing to write loops."""""
a3=np.array(txt.split())
print(type(a3))
print(a3[:15], '\n',len(a3))

<class 'numpy.ndarray'>
['"Here' 'are' 'some' 'of' 'the' 'things' 'you’ll' 'find' 'in' 'NumPy:'
 '•' 'ndarray,' 'an' 'efficient' 'multidimensional'] 
 43


# Arithmetic Operations on Arrays

In [45]:
x=np.array([[6,9,3,5],[1,5,0,6]])
y=np.array([[1,2,3,4],[5,3,2,1]])
add = x+y
sub=x-y
mult=x*y
div=x/y
print(add,'\n',sub,'\n',mult,'\n',div)
print(np.maximum(x,y))
print(np.minimum(x,y))

[[ 7 11  6  9]
 [ 6  8  2  7]] 
 [[ 5  7  0  1]
 [-4  2 -2  5]] 
 [[ 6 18  9 20]
 [ 5 15  0  6]] 
 [[6.         4.5        1.         1.25      ]
 [0.2        1.66666667 0.         6.        ]]
[[6 9 3 5]
 [5 5 2 6]]
[[1 2 3 4]
 [1 3 0 1]]


# Boolean Array

In [17]:
x=np.array([[6,9,3,5],[1,5,0,6]])
y=np.array([[1,2,3,4],[5,3,2,1]])
add = x+y
boolean=(x==y)  #we use boolean array for filtering data
# when we compare 2 arrays through equality operator '='. It goves us a Boolean array in return
print(boolean)
boolean=add>8

arrayfilter1=boolean
print(arrayfilter1)

arrayfilter=add[boolean]
print(arrayfilter)

[[False False  True False]
 [False False False False]]
[[False  True False  True]
 [False False False False]]
[11  9]


# Different Shapes of Array

In [71]:
a4=np.zeros([2,3,5])
print(a4)
print(a4.shape)
print(a4.size)
print(a4.ndim)
print(a4.ravel())
printa4.flatten()

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
(2, 3, 5)
30
3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
a4.fill(3)
a4

array([[[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]],


       [[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]]])

In [41]:
a4[0,2,3,0]=1 #0 indicates 0 n 1 index then2 indicates 0 1 2 index then3 indicates 0 1 2 3 index and then last 0 indicates 0 1 2  3 4 index
a4

array([[[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [1., 9., 9., 9., 9.]]],


       [[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]]])

In [81]:
a5=np.random.rand(5,5,2)
print(a5)
print(a5.shape)
print(a5.ndim)
a5.flatten()
r=a5.reshape(25,2)
print(r)
print(r.shape)
print(r.size)

[[[0.57599622 0.07224621]
  [0.59371462 0.09980974]
  [0.16611594 0.33463599]
  [0.70392147 0.04109214]
  [0.26590773 0.37658154]]

 [[0.48949418 0.0664758 ]
  [0.72049693 0.96858562]
  [0.89560853 0.93220164]
  [0.66926423 0.77915128]
  [0.48041599 0.13389517]]

 [[0.30356262 0.32553491]
  [0.0301912  0.98292973]
  [0.71236202 0.19369329]
  [0.67766605 0.71344668]
  [0.23810005 0.959025  ]]

 [[0.57043414 0.8564727 ]
  [0.21788302 0.76742535]
  [0.56877135 0.23894033]
  [0.71217317 0.78826656]
  [0.80308029 0.88413055]]

 [[0.43188915 0.22290378]
  [0.86715082 0.29803628]
  [0.98968894 0.63611182]
  [0.91295475 0.1855911 ]
  [0.55577951 0.40036513]]]
(5, 5, 2)
3
[[0.57599622 0.07224621]
 [0.59371462 0.09980974]
 [0.16611594 0.33463599]
 [0.70392147 0.04109214]
 [0.26590773 0.37658154]
 [0.48949418 0.0664758 ]
 [0.72049693 0.96858562]
 [0.89560853 0.93220164]
 [0.66926423 0.77915128]
 [0.48041599 0.13389517]
 [0.30356262 0.32553491]
 [0.0301912  0.98292973]
 [0.71236202 0.19369329]
 [0

In [59]:
np.random.shuffle(a5)
a5


array([[0.98139525, 0.08255405, 0.88253804, 0.473489  , 0.99945558],
       [0.23214432, 0.88587875, 0.3750585 , 0.83735347, 0.84249864],
       [0.28097963, 0.96116615, 0.61006715, 0.10074896, 0.557611  ],
       [0.02658959, 0.00590639, 0.99342252, 0.59772761, 0.44875111],
       [0.98566183, 0.03217617, 0.72827979, 0.18269968, 0.47875316]])

In [60]:
a6=np.arange(15)
a6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
a5.ravel()

array([0.98139525, 0.08255405, 0.88253804, 0.473489  , 0.99945558,
       0.23214432, 0.88587875, 0.3750585 , 0.83735347, 0.84249864,
       0.28097963, 0.96116615, 0.61006715, 0.10074896, 0.557611  ,
       0.02658959, 0.00590639, 0.99342252, 0.59772761, 0.44875111,
       0.98566183, 0.03217617, 0.72827979, 0.18269968, 0.47875316])

In [85]:
np.random.seed(2)
print(np.random.rand(3,3))


[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]
 [0.20464863 0.61927097 0.29965467]]


# Transpose and Swapping Axes

In [1]:
import numpy as np
a8=np.random.rand(4,4)
a8

array([[0.00531129, 0.82373828, 0.54609413, 0.52353776],
       [0.47708167, 0.15625368, 0.59387889, 0.55700712],
       [0.35727635, 0.41100302, 0.18857515, 0.33562623],
       [0.02446544, 0.11184894, 0.99371767, 0.44882786]])

In [2]:
a8.T

array([[0.00531129, 0.47708167, 0.35727635, 0.02446544],
       [0.82373828, 0.15625368, 0.41100302, 0.11184894],
       [0.54609413, 0.59387889, 0.18857515, 0.99371767],
       [0.52353776, 0.55700712, 0.33562623, 0.44882786]])

In [3]:
a8.fill(6)
a8

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [10]:
a9=a8.reshape(4,2,2)
a9

array([[[6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.]]])

In [15]:
a9.swapaxes(1,0)


array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [22]:
a11=np.ones([3,4,2,5])

a11

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [30]:
a12=np.array([[[6,9,3,5],[1,5,0,6]],
             [[1,2,3,4],[5,3,2,1]]])
a12.transpose((0,2,1))  #Here 1 2 0 are axeses

array([[[6, 1],
        [9, 5],
        [3, 0],
        [5, 6]],

       [[1, 5],
        [2, 3],
        [3, 2],
        [4, 1]]])

In [40]:
a13=np.array([1.1,2.7])
print(np.rint(a13)) #Round off

[1. 3.]
